.bashrc.d

diff --git a/dot.files/.bashrc.d/functions b/dot.files/.bashrc.d/functions
--- a/dot.files/.bashrc.d/functions
+++ b/dot.files/.bashrc.d/functions
@@ -1,6 +1,8 @@
 # ~/.bashrc.d/functions
 #!/usr/bin/env bash
 
+# UTILS =======================================================================
+
 # Create a new alias
 function mkalias {
     echo "alias $@" >> ${HOME}/.bashrc.d/aliases
@@ -25,6 +27,17 @@ function rmalias {
 #     man "$@"
 # }
 
+# Functions to unify archive management in linux CLI environments
+function compress {
+  case "${1,,}" in
+    *.tar.bz2) tar cjf $@;;
+    *.tar.gz| *.tgz) tar czf $@;;
+    *.zip) zip $@;;
+    *.rar) rar a $@;;
+    *) printf "Cannot operate on unknown file extention \"%s\"\n" "${1}";;
+  esac
+}
+
 ## COMPRESSION FUNCTION ##
 function compress__ {
     FILE=$1
@@ -37,6 +50,22 @@ function compress__ {
         *.rar)     rar $FILE $*      ;;
         *)         echo "Filetype not recognized" ;;
    esac
+}
+
+function extract {
+  case "${1,,}" in # Compare lowercased filename for known extensions.
+    *.7z| *.7za) 7z x "${1}";;
+    *.tar) tar -xf "${1}";;
+    *.tar.gz| *.tar.z| *.tgz) tar -xzf "${1}";;
+    *.tar.bz2| *.tbz2) tar -xjf "${1}";;
+    *.tar.xz| *.txz) tar -Jxf "${1}";;
+    *.bz2) bunzip2 "${1}";;
+    *.rar) rar x "${1}";;
+    *.gz) gunzip "${1}";;
+    *.zip| *.jar) unzip "${1}";;
+    *.z ) uncompress "${1}";;
+    * ) printf "Cannot operate on unknown file extention \"%s\"\n" "${1}" ;;
+  esac
 }
 
 ## EXTRACT FUNCTION ##
@@ -80,6 +109,306 @@ function dtranslate {
             curl dict://dict.org/d:${w}:fd-${i}
         fi
     done
+}
+
+# git add; commit; push
+function gacp {
+  git add .
+  if [[ -n "${1}" ]]; then
+    git commit -m "${1}"
+  else
+    git commit
+  fi
+  git push
+}
+
+# Traverse directory structure given # of steps
+function up {
+  DEEP=$1
+  for i in $(seq 1 ${DEEP:-"1"}); do
+    cd ../
+  done
+}
+
+function listenOnPort {
+  # Returns service listening on given port
+  if [[ -z "${1}" ]]; then
+    printf "port number expected\n"
+    return 1
+  else
+    lsof -n -iTCP:"${1}" |grep LISTEN
+  fi
+}
+
+function checkDirSizes {
+  # Report first params directory sizes in human readable format
+  ls=$(which ls) # Workaround alias
+  du=$(which du)
+  if [[ -x "${ls}" && -x "${du}" ]]; then
+    for d in $( "${ls}" --directory "${1-${HOME}}"/* ); do
+      if [[ -d "${d}" ]]; then
+        "${du}" -hs "${d}"
+      fi
+    done
+  fi
+}
+
+function printMemUsage {
+  #Report Total Used and Available mem in human readable format
+  total=$(cat /proc/meminfo |head -1 |awk '{print $2}')
+  avail=$(cat /proc/meminfo |head -2 |tail -1 |awk '{print $2}')
+  used=$(expr ${total} - ${avail})
+  totalMB=$(expr ${total} / 1024)
+  availMB=$(expr ${avail} / 1024)
+  usedMB=$(expr ${used} / 1024)
+
+  printf "From a total of %dMB, you are using %dMB's, which leaves you with %dMB free memory.\n" ${totalMB} ${usedMB} ${availMB}
+
+}
+
+function updateDate {
+  if [ "${EUID}" -ne "0" ]; then
+    printf "Need root privilages\n"
+    #sudo -l updateDate
+    return 1
+  else
+    ntpdate 0.gentoo.pool.ntp.org
+  fi
+}
+
+function showUptime {
+  echo -ne "${green}$HOSTNAME ${green}uptime is ${green} \t ";uptime | awk /'up/ {print $3,$4,$5,$6,$7,$8,$9,$10}'
+}
+
+function logMeOut {
+  # Call that to logout
+  # Can't log out root like that
+  if [ "${EUID}" -eq "0" ]; then
+    printf "Can't log out root this way\n"
+    return 1
+  else
+    kill -15 -1
+  fi
+}
+
+function pingSubnet {
+  #for x in {1..254}; do
+    for y in {1..254}; do
+      (ping -c 1 -w 2 192.168.1.${y} > /dev/null && echo "UP 192.168.1.${y}" &);
+    done
+  #done
+}
+
+# STRINGS =====================================================================
+
+function alphanumeric_only {
+  printf "%s\n" "${@//[![:alnum:]]}"
+}
+
+function remove_spaces {
+  # https://stackoverflow.com/questions/13659318/how-to-remove-space-from-string
+  echo "${@}"|sed 's/ //g'
+  #shopt -s extglob # Allow extended globbing
+  #var=" lakdjsf   lkadsjf "
+  #echo "${var//+([[:space:]])/}"
+  #shopt -u extglob
+}
+
+function trim {
+  # https://stackoverflow.com/questions/369758/how-to-trim-whitespace-from-a-bash-variable
+    local var="$*"
+    # remove leading whitespace characters
+    var="${var#"${var%%[![:space:]]*}"}"
+    # remove trailing whitespace characters
+    var="${var%"${var##*[![:space:]]}"}"
+    echo -n "$var"
+}
+
+# OLD WALLPAPER-ROTATE ========================================================
+
+#!/usr/bin/env bash
+# wallpaper-rorate
+# tsouchlarakis@gmail.com 2016.10.05
+# Simple script to go through a directory of
+# background images as wallpapers in a timely fashion
+
+declare DEFAULT_WPDIR="${HOME}/.wallpapers" DEFAULT_WAIT="60s" BGSETTER USAGE="\nQuick and dirty script to rotate backgrounds\nin wm's with out such options (ie NOT kde, gnome or xfce4)\nUsage: source wallpaper-rotate && rbgHelperAddDir /home/user/pictures && rotateBg &\n(rbgHelperAddDir /home/user/pictures needs to be executed only once per pictures directory.)\nAlternatively you can source this file in your startup scripts and start it from there.\n"
+
+function rbgHelperAssignDefaults {
+
+  if [[ -x $(which feh) ]]; then # Find a setter or die trying
+    BGSETTER="feh --bg-scale"
+  elif [[ -x $(which wmsetbg) ]]; then
+    BGSETTER="wmsetbg"
+  elif [[ -x $(which fvwm-root) ]]; then
+    BGSETTER="fvwm-root"
+  elif [[ -x $(which fbsetbg) ]]; then
+    BGSETTER="fbsetbg"
+  elif [[ -x $(which bsetbg) ]]; then
+    BGSETTER="bsetbg"
+  elif [[ -x $(which hsetroot) ]]; then
+    BGSETTER="hsetroot -fill"
+  elif [[ -x $(which xsetbg) ]]; then
+    BGSETTER="xsetbg"
+  elif [[ -x $(which xsetroot) ]]; then
+    BGSETTER="xsetroot -bitmap"
+  else
+    echo -e "${USAGE}"
+    return 1
+  fi
+
+  if [[ -r "${HOME}"/.wallpaper.rotate.rc ]]; then # If there is a readable settings file, read it
+    source "${HOME}"/.wallpaper.rotate.rc
+  fi
+
+  if [[ ! -d "${DEFAULT_WPDIR}" ]]; then # Just for the first time
+    mkdir "${DEFAULT_WPDIR}" 2> /dev/null
+  fi
+}
+
+# Helper function to populate "~/.wallpapers" directory with links to image files.
+#
+# First time use of rotateBg, you'll need to run this function first
+# with an image file directory as parameter to initialize "~/.wallpapers".
+# (create "~/.wallpapers" and populate it)
+#
+# Call this function with the dir you'd like to add its images as links in "~/.wallpapers"
+# for use with "rotateBg" function. eg: "rbgHelperAddDir /home/user/pictures"
+function rbgHelperAddDir {
+  rbgHelperAssignDefaults # Check between defaults and settings file
+  for i in $(ls "${1}"); do
+    FE="${i:(-4)}" # Get file extention ${str:(-4)}
+    if [[ "${FE,,}" == ".jpg" || "${FE,,}" == ".jpe" || "${FE,,}" == ".png" || "${FE,,}" == ".gif" || "${FE,,}" == ".bmp" ]]; then # and lowercase it ${str,,}
+      ln -sf "${1}"/"${i}" "${DEFAULT_WPDIR}"/"${i}"
+    fi
+  done
+}
+
+# Helper function to remove links of images from a given directory in "~/.wallpapers"
+#
+# Means to remove a directory (previously added with rbgHelperAddDir /home/user/pictures)
+# from use with "rotateBg"
+#
+# Use this function with the unwanted dir as its sole parameter
+# eg: "rbgHelperRemoveDir /home/user/pictures"
+# It is meant to be called interactively and not from within scripts
+function rbgHelperRemoveDir {
+  rbgHelperAssignDefaults # Check between defaults and settings file
+  for i in $(ls "${1}"); do
+    FE="${i:(-4)}" # Get file extention ${str:(-4)}
+    if [[ "${FE,,}" == ".jpg" || "${FE,,}" == ".jpe" || "${FE,,}" == ".png" || "${FE,,}" == ".gif" || "${FE,,}" == ".bmp" ]]; then # and lowercase it ${str,,}
+      rm -i "${DEFAULT_WPDIR}"/"${i}" # rm --interactive just to play it safe.
+    fi
+  done
+}
+
+function rotateBg {
+  rbgHelperAssignDefaults || return 1 # Assign a WP setter, WP symlink dir and a swap delay
+  WPD=${DEFAULT_WPDIR} # WallPaperDirecroty
+  WPL=( $(ls ${WPD}) ) # fill array with values for WallPaperList
+  WPN=${#WPL[*]} # get array upper bound as WallPapersNumber
+  while [[ true ]]; do
+    #let "RN = $RANDOM % $WPN" # limit a random num to upper array bounds
+    RN=$(shuf -n 1 -i 0-"${WPN}") # by using shuf instead of $RANDOM as a RundomNumber
+    WP="${WPD}/${WPL[$RN]}" # Get path and name of image as a selected WallPaper
+    if [[ -L "${WP}" ]]; then # Check if item is a symlink (accidents do happen)
+      ${BGSETTER} "${WP}" # set wallpaper, wait
+      sleep ${DEFAULT_WAIT}
+    fi
+  done
+}
+
+# CHUBIN WORKS ================================================================
+
+function cheat_sh {
+  # https://github.com/chubin/cheat.sh
+  curl cheat.sh/${1}
+}
+
+function rate_sx {
+  # https://twitter.com/igor_chubin
+  curl ${1-"usd"}.rate.sx
+}
+
+function wttr_in {
+  # https://twitter.com/igor_chubin # Try wttr moon
+  curl wttr.in/${1-"Athens"}
+}
+
+#
+# function accuWeather {
+#   # http://www.accuweather.com/
+#   URL='http://www.accuweather.com/en/gr/athens/182536/weather-forecast/182536'
+#   wget -q -O- "$URL" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $2": "$16", "$12"°" }'| head -1
+# }
+#
+
+# GAMES =======================================================================
+
+function rps {
+  # Rock Paper Scissors mt 20170525
+
+  declare -a op=("Rock" "Paper" "Scissors") oc=("WIN" "Defeat" "Draw")
+
+  declare -A rs[0,0]=${oc[2]} rs[0,1]=${oc[1]} rs[0,2]=${oc[0]} rs[1,0]=${oc[0]} rs[1,1]=${oc[2]} rs[1,2]=${oc[1]} rs[2,0]=${oc[1]} rs[2,1]=${oc[0]} rs[2,2]=${oc[2]}
+
+  declare cs=0 us=0 ns=0 rd=0
+
+  printf "Hello! Welcome to %s %s %s Game!\n" ${op[0]} ${op[1]} ${op[2]}
+
+  while [ true ]; do
+
+    read -e -p "${op[0]}:1, ${op[1]}:2, ${op[2]}:3, Quit:0. What's your pick?: " ui
+
+    case ${ui} in
+      0)
+        if [ $us -gt $cs ] ; then
+          bbmsg="${oc[0]}"
+        elif [ $us -lt $cs ] ; then
+          bbmsg="got ${oc[1]}ed by"
+        elif [ $us -eq $cs ] ; then
+          bbmsg="${oc[2]}ed with"
+        fi
+
+        printf "After %d rounds, you %s the CPU with %d:%d points and %d ties.\n" $rd ${bbmsg} $us $cs $ns
+
+        return 0 ;;
+
+      [1-3])
+        let "rd++"
+        let "ui--"
+
+        ci=$(shuf -i 0-2 -n 1)
+
+        printf "Round : %d is a %s. You selected %s, while the CPU rolled %s\n" $rd ${rs[${ui},${ci}]}  ${op[${ui}]} ${op[${ci}]}
+
+        case ${rs[${ui},${ci}]} in
+          ${oc[0]}) let "us++";;
+          ${oc[1]}) let "cs++";;
+          ${oc[2]}) let "ns++";;
+        esac
+
+        printf "Player : %d, CPU : %d, Ties : %d\n" $us $cs $ns ;;
+
+      *)
+        printf "Choose again from 0 to 3\n" ;;
+
+    esac
+
+  done
+}
+
+function russianRulette {
+  # https://www.facebook.com/freecodecamp/photos/a.1535523900014339.1073741828.1378350049065059/2006986062868118/?type=3&theater
+  # [ $[ $RANDOM % 6 ] == 0 ] && echo "BOOM!!!" || echo "LUCKY GUY!!!"
+
+  let "RV = $RANDOM % 6";
+
+  if [[ $RV == 0 ]]; then
+    echo "BOOM!!! You've rolled a ${RV}"
+  else
+    echo "LUCKY GUY!!! You've rolled a ${RV}"
+  fi
 }
 
 function color_test {
@@ -128,7 +457,7 @@ function fancy_pacman {
 	inv=$'\e[7m'
 
 
-cat << EOF
+  cat << EOF
 
 $rst
  $f3  ▄███████▄                $f1  ▄██████▄    $f2  ▄██████▄    $f4  ▄██████▄    $f5  ▄██████▄    $f6  ▄██████▄
